=== danive97/Prueba-DIS/PracticaDIS/videotecas.dtd
<!--Dani Ojeda-->
        <!--Aquí se crea el DTD, generado a partir del XML (videotecas.xml)-->
        <?xml encoding="UTF-8"?>
        <!--Defino un elemento "videotecas" que contiene un subelemento "videoteca" y que puede ser opcional-->
        <!ELEMENT videotecas (videoteca)*>
        <!--Defino un elemento "videoteca" que contiene varios subelementos-->
        <!--nombre, ubicación... y que pueden ser opcionales-->
        <!ELEMENT videoteca (nombre|ubicacion|fecha_ult_actualizacion|peliculas)*>
        <!--Defino los siguientes elementos: nombre, ubicacion y fecha_ult_actualizacion-->
        <!ELEMENT nombre (#PCDATA)><!--el PCDATA, nos indica que puede contener texto entre las etiquetas-->
        <!ELEMENT ubicacion (#PCDATA)>
        <!ELEMENT fecha_ult_actualizacion (#PCDATA)>
        <!--Defino un elemento "peliculas" que contiene un subelemento "pelicula" y que puede ser opcional-->
        <!ELEMENT peliculas (pelicula)*>
        <!--Defino un elemento "pelicula" que contiene varios subelementos-->
        <!--titulo, sinopsis, genero, enlace_IMDB... y que pueden ser opcionales-->
        <!ELEMENT pelicula (titulo|sinopsis|genero|enlace_IMDB|reparto)*>
        <!--Defino una lista de atributos para "pelicula"-->
        <!--Defino un elemento "pelicula" que contiene varios subelementos-->
        <!ATTLIST pelicula
                estreno CDATA #REQUIRED
                id CDATA #REQUIRED
                minutos CDATA #REQUIRED>
        <!--Defino los siguientes elementos: nombre, ubicacion y fecha_ult_actualizacion-->
        <!ELEMENT titulo (#PCDATA)><!--el PCDATA, nos indica que puede contener texto entre las etiquetas-->
        <!ELEMENT sinopsis (#PCDATA)>
        <!ELEMENT genero (#PCDATA)?>
        <!ELEMENT enlace_IMDB (#PCDATA)>
        <!--Defino un elemento "reparto" que contiene varios subelementos-->
        <!ELEMENT reparto (actor)*><!--El elemento "reparto" va a contener, un subelemento "actor" que puede ser opcional-->
        <!ELEMENT actor (nombre|enlace_wiki)*><!--Mi elemento "actor", contiene dos elementos nombre y enlace_wiki-->
        <!ELEMENT enlace_wiki (#PCDATA)>

=== danive97/Prueba-DIS/PracticaDIS/videotecas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE videotecas SYSTEM "videotecas.dtd">
<videotecas>
    <videoteca>
        <nombre>Peliculas Star Wars</nombre>
        <ubicacion>Salon</ubicacion>
        <fecha_ult_actualizacion>14/11/2020</fecha_ult_actualizacion>
        <peliculas>
           <pelicula id="1" minutos="136" estreno="1999" >
               <titulo>Star Wars: Episodio I - La amenaza fantasma</titulo>
               <sinopsis>La trama describe la historia del maestro jedi Qui-Gon Jinn y de su aprendiz Obi-Wan Kenobi, que escoltan y protegen a la Reina Amidala desde su planeta Naboo hasta Coruscant con la esperanza de encontrar una salida pacífica a un conflicto comercial interplanetario a gran escala. También trata del joven Anakin Skywalker antes de convertirse en Jedi, presentado como un esclavo con un potencial de la Fuerza inusualmente fuerte, y debe lidiar con el misterioso regreso de los Sith.
               </sinopsis>
               <enlace_IMDB>https://www.imdb.com/title/tt0120915/?ref_=nv_sr_srsg_6</enlace_IMDB>
               <genero>Space Opera</genero>
               <reparto>
                   <actor>
                       <nombre>Liam Neeson</nombre>
                       <enlace_wiki>https://es.wikipedia.org/wiki/Liam_Neeson</enlace_wiki>
                   </actor>
                   <actor>
                       <nombre>Samuel Leroy Jackson</nombre>
                       <enlace_wiki>https://es.wikipedia.org/wiki/Samuel_L._Jackson</enlace_wiki>
                   </actor>
                   <actor>
                       <nombre>Ewan McGregor</nombre>
                       <enlace_wiki>https://es.wikipedia.org/wiki/Ewan_McGregor</enlace_wiki>
                   </actor>
               </reparto>
           </pelicula>
            <pelicula id="2" minutos="142" estreno="2002" >
                <titulo>Star Wars: Episodio II - El ataque de los clones</titulo>
                <sinopsis>La trama se desarrolla diez años después de los sucesos ocurridos en la película anterior, La amenaza fantasma. Después de la Batalla de Naboo, la galaxia se encuentra al borde de una guerra civil. Bajo la dirección de un Jedi renegado que se hace llamar Conde Dooku, muchos sistemas solares amenazan con la secesión de la República Galáctica. Tras los intentos de asesinato de la senadora Padmé Amidala, la anterior reina de Naboo, el Padawan Anakin Skywalker es asignado para protegerla, mientras que a su maestro, Obi-Wan Kenobi, se le asigna la investigación del intento de asesinato.
                </sinopsis>
                <enlace_IMDB>https://www.imdb.com/title/tt0121765/?ref_=nv_sr_srsg_7</enlace_IMDB>
                <genero>Space Opera</genero>
                <reparto>
                    <actor>
                        <nombre>Ewan McGregor</nombre>
                        <enlace_wiki>https://es.wikipedia.org/wiki/Ewan_McGregor</enlace_wiki>
                    </actor>
                    <actor>
                        <nombre>Natalie Portman</nombre>
                        <enlace_wiki>https://es.wikipedia.org/wiki/Natalie_Portman</enlace_wiki>
                    </actor>
                </reparto>
            </pelicula>
            <pelicula id="3" minutos="139" estreno="2005" >
                <titulo>Star Wars: Episodio III - La venganza de los Sith</titulo>
                <sinopsis>La trama describe una época en la que los Caballeros Jedi se han esparcido por toda la galaxia, dirigiendo un ejército clon masivo para enfrentar a los Separatistas Galácticos, tres años después del inicio de las Guerras Clon. El Canciller Palpatine fue secuestrado y el Maestro Jedi Obi-Wan Kenobi, acompañado de su aprendiz Anakin Skywalker, es enviado a rescatarlo en una misión, donde también debe eliminar a los Líderes Separatistas, el Conde Dooku y el General Grievous, para concluir el conflicto galáctico. Después de ser rescatado, el Canciller fortalece su amistad con Anakin, para poder convencerlo de que existen mayores beneficios en el Lado Oscuro de la Fuerza, que del Lado Luminoso. La Orden Jedi empieza a sospechar de la amistad entre el Canciller y Anakin, por lo que intenta averiguar los verdaderos objetivos de Palpatine. Cuando el Canciller se descubre, repentinamente, como el siniestro Lord Sith Darth Sidious, los destinos de la Orden Jedi y de la República Galáctica se encuentran expuestos ante un inminente peligro.
                </sinopsis>
                <enlace_IMDB>https://www.imdb.com/title/tt0121766/?ref_=fn_tt_tt_9</enlace_IMDB>
                <genero>Space Opera</genero>
                <reparto>
                    <actor>
                        <nombre>Ewan McGregor</nombre>
                        <enlace_wiki>https://es.wikipedia.org/wiki/Ewan_McGregor</enlace_wiki>
                    </actor>
                    <actor>
                        <nombre>Ian McDiarmid</nombre>
                        <enlace_wiki>https://es.wikipedia.org/wiki/Ian_McDiarmid</enlace_wiki>
                    </actor>
                </reparto>
            </pelicula>
            <pelicula id="4" minutos="121" estreno="1977" >
                <titulo>Star Wars: Episodio IV - Una nueva esperanza</titulo>
                <sinopsis>La trama describe la historia de un grupo de guerrilleros —conocidos como la Alianza Rebelde— cuyo objetivo es destruir la estación espacial Estrella de la Muerte, creada por el opresor Imperio Galáctico. Desde una perspectiva general, la historia se enfoca en un joven granjero llamado Luke Skywalker, quien, de forma repentina, se convertirá en un héroe conforme acompaña al Maestro Jedi Obi-Wan Kenobi en una misión que lo llevará a unirse a la Alianza Rebelde para ayudarles a destruir la estación espacial del Imperio.
                </sinopsis>
                <enlace_IMDB>https://www.imdb.com/title/tt0076759/?ref_=nv_sr_srsg_3</enlace_IMDB>
                <genero>Space Opera</genero>
                <reparto>
                    <actor>
                        <nombre>Mark Hamill</nombre>
                        <enlace_wiki>https://es.wikipedia.org/wiki/Mark_Hamill</enlace_wiki>
                    </actor>
                    <actor>
                        <nombre>Harrison Ford</nombre>
                        <enlace_wiki>https://es.wikipedia.org/wiki/Harrison_Ford</enlace_wiki>
                    </actor>
                </reparto>
            </pelicula>
            <pelicula id="5" minutos="124" estreno="1980" >
                <titulo>Star Wars: Episodio V - El Imperio contraataca</titulo>
                <sinopsis>La ficción de la película se sitúa tres años después de la destrucción de la estación espacial de combate conocida como la Estrella de la muerte, destrucción acaecida al final del episodio anterior, Una Nueva Esperanza, estrenada en el año 1977. En El Imperio contraataca Luke Skywalker, Han Solo, Leia Organa y el resto de la Alianza Rebelde son perseguidos por Darth Vader y las fuerzas de élite del Imperio Galáctico. En este episodio se desarrolla la historia de amor entre Han y Leia, mientras que Luke aprende más sobre los caminos de la Fuerza de la mano del maestro Yoda. Con Han y Leia capturados por el Imperio, Luke luchará contra Darth Vader en una confrontación sin igual, pero Vader esconde una terrible revelación.
                </sinopsis>
                <enlace_IMDB>https://www.imdb.com/title/tt0080684?ref_=nv_sr_srsg_0</enlace_IMDB>
                <genero>Space Opera</genero>
                <reparto>
                    <actor>
                        <nombre>Mark Hamill</nombre>
                        <enlace_wiki>https://es.wikipedia.org/wiki/Mark_Hamill</enlace_wiki>
                    </actor>
                    <actor>
                        <nombre>Harrison Ford</nombre>
                        <enlace_wiki>https://es.wikipedia.org/wiki/Harrison_Ford</enlace_wiki>
                    </actor>
                </reparto>
            </pelicula>
            <pelicula id="6" minutos="131" estreno="1983" >
                <titulo>Star Wars: Episode VI - Return of the Jedi</titulo>
                <sinopsis>En Sombras del Imperio, se revela que el Imperio ha comenzado la construcción en secreto de la Segunda Estrella de la Muerte, mucho más poderosa, grande, armada y mejor defendida que la versión anterior, con un escudo de energía que la convierte en una estación espacial invisible a los sensores y sistemas de ataque de otras naves de combate. Siguiendo los consejos del Príncipe Xizor, el Emperador Palpatine deja que los planos caigan en las manos de los rebeldes, en una batalla donde logran capturar una nave de transporte. Los Espías Bothan descubren la nave que resguarda los mencionados planos y aunque muchos de ellos mueren en combate, logran divulgar la información a la Rebelión, de su diseño, capacidad, armamento, defensa y ubicación exacta en la Galaxia, para comenzar el plan de Ataque contra la nueva Estrella de la Muerte, y que la flota estelar del Imperio está dispersa por la Galaxia, buscando a la rebelión entre todos los sistemas estelares.
                </sinopsis>
                <enlace_IMDB>https://www.imdb.com/title/tt0086190/?ref_=nv_sr_srsg_0</enlace_IMDB>
                <genero>Space Opera</genero>
                <reparto>
                    <actor>
                        <nombre>Mark Hamill</nombre>
                        <enlace_wiki>https://es.wikipedia.org/wiki/Mark_Hamill</enlace_wiki>
                    </actor>
                    <actor>
                        <nombre>Harrison Ford</nombre>
                        <enlace_wiki>https://es.wikipedia.org/wiki/Harrison_Ford</enlace_wiki>
                    </actor>
                    <actor>
                        <nombre>Carrie Fisher</nombre>
                        <enlace_wiki>https://es.wikipedia.org/wiki/Carrie_Fisher</enlace_wiki>
                    </actor>
                </reparto>
            </pelicula>
